name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      system_update:
        description: "Set to true to install patches and updates"
        required: false
        default: "false"

jobs:
  run-playbook:
    runs-on: self-hosted
    container:
      image: ghcr.io/codemonkey-science/ansible-ci-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    env:
      ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CONFIG: ansible/ansible.cfg
      SYSTEM_UPDATE: ${{ github.event.inputs.system_update || 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write private key to disk
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          . ansible-env/bin/activate
          cd $GITHUB_WORKSPACE
          ansible-playbook -i ansible/inventory ansible/site.yml \
            --extra-vars "ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=${{ env.SYSTEM_UPDATE }}"