name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      system_update:
        description: "Set to true to install patches and updates"
        required: false
        default: "false"

jobs:
  run-playbook:
    runs-on: self-hosted
    container: ghcr.io/codemonkey-science/ansible-ci-image:latest

    env:
      ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_LOCAL_TEMP: /home/ansible/.ansible/tmp
      ANSIBLE_REMOTE_TEMP: /home/ansible/.ansible/tmp
      SYSTEM_UPDATE: ${{ github.event.inputs.system_update || 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write private key to disk
        run: |
          mkdir -p /home/ansible/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" | tee /home/ansible/.ssh/id_rsa > /dev/null
          chmod 600 /home/ansible/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          bash -c "
          whoami
          ls -la /github/home/.ansible/
          cd ~
          . /home/ansible/ansible-env/bin/activate
          cd $GITHUB_WORKSPACE
          ansible-playbook -vvv -i ansible/inventory ansible/site.yml \
            --extra-vars 'ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=${{ env.SYSTEM_UPDATE }}'
          "