name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      system_update:
        description: "Set to true to install patches and updates"
        required: false
        default: "false"

jobs:
  run-playbook:
    runs-on: self-hosted
    container: ghcr.io/codemonkey-science/ansible-ci-image:latest

    env:
      HOME: /home/ansible
      TMPDIR: /tmp
      ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_LOCAL_TEMP: /home/ansible/.ansible/tmp
      ANSIBLE_REMOTE_TEMP: /home/ansible/.ansible/tmp
      SYSTEM_UPDATE: ${{ github.event.inputs.system_update || 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Environment Variables and Permissions
        run: |
          echo "Environment Variables:"
          echo "----------------------------------------------------------------------"
          printenv
          echo "----------------------------------------------------------------------"
          echo ""
          echo "Permissions:"
          echo "----------------------------------------------------------------------"
          echo "\$HOME:"
          ls -ld $HOME
          echo ""
          echo "/github"
          ls -ld /github
          echo ""
          echo "/home/ansible"
          ls -ld /home/ansible

      - name: Write private key to disk
        run: |
          mkdir -p /home/ansible/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" | tee /home/ansible/.ssh/id_rsa > /dev/null
          chmod 600 /home/ansible/.ssh/id_rsa

      - name: Set up Ansible temp folders
        run: |
          mkdir -p /home/ansible/.ansible/tmp
          chmod 700 /home/ansible/.ansible/tmp
          mkdir -p /home/ansible/.ansible/cp
          chmod 700 /home/ansible/.ansible/cp

      - name: Verify remote_tmp directory
        run: |
          echo "Remote Temp Directory:"
          ls -ld /tmp
        
      - name: Run Ansible Playbook
        run: |
          whoami
          ls -la /github/home/.ansible/
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          cd ~
          . /home/ansible/ansible-env/bin/activate
          cd $GITHUB_WORKSPACE
          ansible-playbook -v -i ansible/inventory ansible/site.yml \
            --extra-vars 'ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=${{ env.SYSTEM_UPDATE }}'

      - name: Remove private key from disk
        run: |
          if [ -f /home/ansible/.ssh/id_rsa ]; then
            rm -f /home/ansible/.ssh/id_rsa || { echo "Failed to delete private key"; exit 1; }
            if [ ! -f /home/ansible/.ssh/id_rsa ]; then
              echo "Private key successfully deleted"
            else
              echo "Failed to delete private key"; exit 2;
            fi
          else
            echo "Private key does not exist for some reason. Nothing to delete. Please investigate."
            exit 3
          fi
