name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: self-hosted

    env:
      ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker container
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu:latest
        options: -v ${{ github.workspace }}:/workspace
        run: |
          apt-get update
          apt-get install -y python3-pip sshpass
          python3 -m pip install --upgrade pip
          pip install ansible
          cd /workspace
          ansible-playbook -i inventory site.yml --extra-vars "ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=true"