name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      system_update:
        description: "Set to true to install patches and updates"
        required: false
        default: "false"

jobs:
  run-playbook:
    runs-on: self-hosted

    env:
      ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CONFIG: ansible/ansible.cfg
      SYSTEM_UPDATE: ${{ github.event.inputs.system_update || 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker container
        uses: actions/checkout@v2
        with:
          # Ensure the repository is checked out in the default workspace
          path: /home/ansible/workspace

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/codemonkey-science/ansible-ci-image:latest

      - name: Run Ansible Playbook
        uses: docker://ghcr.io/codemonkey-science/ansible-ci-image:latest
        with:
          args: >
            ansible-playbook -i ansible/inventory ansible/site.yml
            --extra-vars "ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=${{ env.SYSTEM_UPDATE }}"
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_CONFIG: ansible/ansible.cfg
          SYSTEM_UPDATE: ${{ github.event.inputs.system_update || 'false' }}

      - name: Write private key to disk
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          . ansible-env/bin/activate
          cd $GITHUB_WORKSPACE
          ansible-playbook -i ansible/inventory ansible/site.yml \
            --extra-vars "ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=${{ env.SYSTEM_UPDATE }}"