name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: self-hosted
    container: ubuntu:latest

    env:
      ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip python3-venv sshpass

    - name: Set up virtual environment and install Ansible
      run: |
        python3 -m venv ansible-env
        . ansible-env/bin/activate
        pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: |
        . ansible-env/bin/activate
        cd $GITHUB_WORKSPACE
        ansible-playbook -i ansible/inventory ansible/site.yml --extra-vars "ANSIBLE_BECOME_PASS=${{ secrets.ANSIBLE_BECOME_PASS }} system_update=true"